# Generated by Django 3.1.7 on 2021-04-10 14:51

from django.db import migrations, models
import programing.models


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0002_auto_20210410_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='profile_image/default.jpg', upload_to=programing.models.profile_image),
        ),
    ]
