# Generated by Django 3.1.7 on 2021-04-11 13:16

from django.db import migrations, models
import programing.models


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0003_auto_20210410_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='profile_image/default.jpeg', upload_to=programing.models.profile_image),
        ),
    ]
