# Generated by Django 3.1.7 on 2021-04-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0004_auto_20210411_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
