# Generated by Django 3.1.7 on 2021-04-13 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programing', '0007_auto_20210413_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanguage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='c_problem',
        ),
        migrations.AddField(
            model_name='profile',
            name='c_problem',
            field=models.ManyToManyField(to='programing.CLanguage'),
        ),
    ]
