# Generated by Django 3.1.7 on 2021-04-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0008_auto_20210413_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='c_problem',
            field=models.ManyToManyField(related_name='clanguage', to='programing.CLanguage'),
        ),
    ]
