# Generated by Django 3.1.7 on 2021-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0009_auto_20210413_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='c_problem',
        ),
        migrations.AddField(
            model_name='profile',
            name='c_problem',
            field=models.ForeignKey(default=1, on_delete=set, related_name='clanguage', to='programing.clanguage'),
            preserve_default=False,
        ),
    ]
