# Generated by Django 3.1.7 on 2021-04-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0010_auto_20210413_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='c_problem',
        ),
    ]
