# Generated by Django 3.1.7 on 2021-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0011_remove_profile_c_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanguage',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
