# Generated by Django 3.1.7 on 2021-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0012_clanguage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanguage',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
