# Generated by Django 3.1.7 on 2021-04-13 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programing', '0013_auto_20210413_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='c_problem',
            field=models.ManyToManyField(related_name='clanguage', to='programing.CLanguage'),
        ),
        migrations.AlterField(
            model_name='clanguage',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_posts', to='account.user'),
            preserve_default=False,
        ),
    ]
