# Generated by Django 3.1.7 on 2021-04-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0014_auto_20210413_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='c_problem',
            new_name='title',
        ),
    ]
