# Generated by Django 3.1.7 on 2021-04-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0018_auto_20210413_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.AddField(
            model_name='clanguage',
            name='user',
            field=models.ManyToManyField(to='programing.Profile'),
        ),
    ]
