# Generated by Django 3.1.7 on 2021-04-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0020_auto_20210413_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='CLanguage',
        ),
    ]
