# Generated by Django 3.1.7 on 2021-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programing', '0023_auto_20210414_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanguage',
            name='lavel',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'medium'), ('Hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
